service: nuss-serverless-app-project-5

#frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  profile: nusschallenge
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  createDevice:
    handler: upload/index.createDeviceHandler
    memory: 1024
    timeout: 30
    events:
      - http:
          method: post
          path: devices
          cors: true
          integration: lambda-proxy
  getDevice:
    handler: upload/index.getDeviceHandler
    memory: 1024
    timeout: 30
    events:
      - http:
          method: get
          path: devices/{deviceId}
          cors: true
          integration: lambda-proxy
  getAllDevice:
    handler: upload/index.getAllDeviceHandler
    memory: 1024
    timeout: 30
    events:
      - http:
          method: get
          path: devices
          cors: true
          integration: lambda-proxy
resources:
  Resources:
   DynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: deviceId
            AttributeType: S
        KeySchema:
          - AttributeName: deviceId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
